// <auto-generated />
using System;
using AT_Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AT_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231117091032_RemoveSubscription")]
    partial class RemoveSubscription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.24");

            modelBuilder.Entity("AT_Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aff86cec-4257-464d-b48c-0bab6a5d9b8f"),
                            CreatedAt = new DateTime(2023, 11, 17, 9, 10, 32, 120, DateTimeKind.Utc).AddTicks(8614),
                            Password = "$2a$11$bKpyKOdeCAv3Y3ueqHb.duDw8qj9mOwVkGnTi2bgvNoFvQavC6RvW",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
