// <auto-generated />
using System;
using GGregator_Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GGregator_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231117091611_ForgotWhatThatOneIsDoing")]
    partial class ForgotWhatThatOneIsDoing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.24");

            modelBuilder.Entity("GGregator_Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3325b48-a690-4839-91bd-8bf1d60dca6c"),
                            CreatedAt = new DateTime(2023, 9, 17, 19, 19, 19, 97, DateTimeKind.Utc),
                            IsAdmin = true,
                            IsSubscribed = true,
                            Password = "$2a$11$uCBSToyuBC9QsjgVWoiuDO8ttnnvK4eW.I8XrxVFeIGsUJm/WP0O6",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
